In [2]:
import numpy
from scipy import ndimage

In [4]:
m = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
w = numpy.array([[0,1,0],[1,1,1],[0,1,0]])

In [5]:
conv = ndimage.convolve(m,w,mode='constant', cval=0)
corr = ndimage.correlate(m,w,mode='constant', cval=0)

print(conv)
print(corr)
print(numpy.array_equal(conv, corr))

[[ 7 11 11]
 [17 25 23]
 [19 29 23]]
[[ 7 11 11]
 [17 25 23]
 [19 29 23]]
True
